stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - artifacts/raw/

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - config/paths_config.py
    outs:
      - artifacts/models/fasterrcnn.pth